
export const ADD_MESSAGE_ACTION = 'ADD_MESSAGE_ACTION';
export const LOAD_MESSAGES_PENDING_ACTION = 'LOAD_MESSAGES_PENDING_ACTION';
export const LOAD_MESSAGES_SUCCES_ACTION = 'LOAD_MESSAGES_SUCCES_ACTION';
export const LOAD_MESSAGES_ERROR_ACTION = 'LOAD_MESSAGES_ERROR_ACTION';
export const REMOVE_MESSAGE_SUCCESS_ACTION = 'REMOVE_MESSAGE_SUCCESS_ACTION';
export const REMOVE_MESSAGE_ERROR_ACTION = 'REMOVE_MESSAGE_ACTION';





